### ISSUE TITLE
NPM package owneship

### ISSUE THREAD

**Issue by indirect** [tachyons-css/tachyons-verbose#6]
So uh... hi @hongkonggong! (Since you probably don't recognize me on the internets, we met in January when I was visiting HK with @sailorhg 😬👋🏻). Anyway, after looking for an npm package named `tachyons-verbose` and not finding one, I checked out this repo and idly ran `npm publish`... and discovered I now accidentally own https://www.npmjs.com/package/tachyons-verbose. Let me know if you want me to make you the owner on NPM or whatever. Thanks for working on this!

**Comment by adrawerofthings** [comment]
Oh hai friend! I am 🤩 that you use/play around with my package! (Ahem. Pun unintended.) I suppose make me a co-owner? My npm username should be `hongkonggong`.

Silly question – does that mean I should be running `npm publish` every time I update the repo as well? (Am a npm n00b 😭)

**Comment by indirect** [comment]
Awesome, I added you to the package. It's not required to run `npm publish` when you make changes, but if you do, everyone will be able to `npm install --save tachyons-verbose`! You may also need to bump the version in order to publish a new package each time... I think [`npm version`](https://docs.npmjs.com/cli/version) can automate that.
